import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { buildInternalEan, ean13CheckDigit, generateUniqueInternalEan } from '../src/shared/internal-ean';
import { translations } from '../src/renderer/i18n/translations';

const root = resolve(__dirname, '..');
const source = (path: string) => readFileSync(resolve(root, path), 'utf8');

describe('internal EAN generator', () => {
  it('computes the standard EAN-13 check digit', () => {
    expect(ean13CheckDigit('590123412345')).toBe('7'); // known-valid 5901234123457
    expect(ean13CheckDigit('200000000000')).toBe('8');
    expect(() => ean13CheckDigit('123')).toThrow();
  });

  it('mints codes shaped like the backend generator: 2 + salonCode + 7 digits + check', () => {
    for (let i = 0; i < 20; i++) {
      const ean = buildInternalEan('6536');
      expect(ean).toMatch(/^26536\d{8}$/);
      expect(ean).toHaveLength(13);
      expect(ean13CheckDigit(ean.slice(0, 12))).toBe(ean[12]);
    }
    expect(() => buildInternalEan('65')).toThrow();
  });

  it('regenerates automatically on collision and gives up after the attempt budget', () => {
    const seen: string[] = [];
    let collisions = 3;
    const result = generateUniqueInternalEan('6536', (candidate) => {
      seen.push(candidate);
      return collisions-- > 0; // first three candidates are "taken"
    });
    expect(result).toBe(seen[3]);
    expect(seen.length).toBe(4);

    expect(generateUniqueInternalEan('6536', () => true, 5)).toBeNull();
  });
});

describe('internal EAN wiring contract', () => {
  it('flows salonCode through the capabilities whitelist mapper', () => {
    const apiClient = source('src/main/network/api-client.ts');
    const types = source('src/shared/types.ts');

    expect(apiClient).toContain("salonCode: typeof raw?.salonCode === 'string'");
    expect(types).toContain('salonCode?: string | null');
  });

  it('offers the generate button in create + edit and auto-retries a backend duplicate', () => {
    const createDialog = source('src/renderer/components/products/ProductCreateDialog.tsx');
    const editForm = source('src/renderer/components/products/ProductEditForm.tsx');
    const moduleSource = source('src/renderer/components/products/ProductModule.tsx');

    for (const form of [createDialog, editForm]) {
      expect(form).toContain('generateUniqueInternalEan');
      expect(form).toContain('products.barcode.generate');
    }
    // Cross-till race: regenerate + FRESH idempotency key, then retry.
    expect(createDialog).toContain('duplicateBarcode && barcodeAutoGenerated && salonCode');
    expect(createDialog).toContain('attemptKey = makeIdempotencyKey()');
    // Collision check covers the whole catalog incl. inactive rows.
    expect(moduleSource).toContain('const isBarcodeTaken = useCallback');
    expect(moduleSource).toContain('findDuplicateBarcodeSet(code, allProducts)');
  });

  it('translates the generator copy in EN/VI/PL', () => {
    for (const language of ['en', 'vi', 'pl'] as const) {
      for (const key of ['products.barcode.generate', 'products.barcode.generatedHint', 'products.barcode.generateFailed']) {
        expect(translations[language][key], `${language}.${key}`).toBeTruthy();
      }
    }
  });
});
